# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _

NEWSTATUS_CHOICES = (
    ('AF', 'Afiliado'),
    ('SI', 'Simpatizante'),
)

STATUS_CHOICES = (
    ('PA', 'Preafiliado'),
    ('AF', 'Afiliado'),
    ('PS', 'Presimpatizante'),
    ('SI', 'Simpatizante'),
    ('IN', 'Indeterminado'),
)

PAYMENT_CHOICES = (
    ('CU', 'Cuota'),
    ('DO', 'Donación'),
    ('OT', 'Otros'),
)

METHOD_CHOICES = (
    ('PP', _('PayPal')),
    ('DI', _('Direct')),
    ('TR', _('Transfer')),
)

DOC_CHOICES = (
    ('DNI', 'Doc. Nacional Identidad'),
    ('NIE', 'Núm. Identif. Extranjero'),
    ('TRJ', 'Tarjeta Res. Comunitaria'),
)

ACCEPT_CHOICES = (
    (False, _('No')),
    (True, _('Yes')),
)

ACCEPTONE_CHOICES = (
    ('N', _('No')),
    ('Y', _('Yes')),
)

CONTACT_CHOICES = (
    ('E', 'Email'),
    ('W', 'Telefono (Trabajo)'),
    ('H', 'Telefono (Casa)'),
    ('m', 'Telefono (Móvil)'),
    ('F', 'Telefono (Fax)'),
    ('V', 'Telefono (VoIP)'),
    ('S', 'Skype'),
    ('A', 'AIM/ICQ'),
    ('B', 'Bonjour'),
    ('I', 'IRC'),
    ('J', 'Jabber'),
    ('G', 'Gmail'),
    ('g', 'Groupwise'),
    ('M', 'MSN'),
    ('Q', 'QQ'),
    ('X', 'Simple'),
    ('Y', 'Yahoo'),
)

PROVINCE_CHOICES = (
    ('ALA', 'Álava'), 
    ('ALB', 'Albacete'),
    ('ALI', 'Alicante'),
    ('ALM', 'Almerí­a'),
    ('AST', 'Asturias'),
    ('AVI', 'Ávila'),
    ('BAD', 'Badajoz'),
    ('BAR', 'Barcelona'),
    ('BUR', 'Burgos'),
    ('CAC', 'Cáceres'),
    ('CAD', 'Cádiz'),
    ('CAN', 'Cantabria'),
    ('CAS', 'Castellón'),
    ('CIU', 'Ciudad Real'),
    ('COR', 'Córdoba'),
    ('ACO', 'La Coruña'),
    ('CUE', 'Cuenca'),
    ('GIR', 'Gerona'),
    ('GRA', 'Granada'),
    ('GUA', 'Guadalajara'),
    ('GUI', 'Guipüzcoa'),
    ('HUE', 'Huelva'),
    ('HUS', 'Huesca'),
    ('IBA', 'Islas Baleares'),
    ('JAE', 'Jaén'),
    ('LEO', 'León'),
    ('LER', 'Lérida'),
    ('LUG', 'Lugo'),
    ('MAD', 'Madrid'),
    ('MAL', 'Málaga'),
    ('MUR', 'Murcia'),
    ('NAV', 'Navarra'),
    ('ORE', 'Orense'),
    ('PAL', 'Palencia'),
    ('LPA', 'Las Palmas'),
    ('PON', 'Pontevedra'),
    ('LRI', 'La Rioja'),
    ('SAL', 'Salamanca'),
    ('SCT', 'Santa Cruz de Tenerife'),
    ('SEG', 'Segovia'),
    ('SEV', 'Sevilla'),
    ('SOR', 'Soria'),
    ('TAR', 'Tarragona'),
    ('TER', 'Teruel'),
    ('TOL', 'Toledo'),
    ('VAL', 'Valencia'),
    ('VLL', 'Valladolid'),
    ('VIZ', 'Vizcaya'),
    ('ZAM', 'Zamora'),
    ('ZAR', 'Zaragoza'),
)

COUNTRY_CHOICES = (
    ('afg', 'Afganistán'),
    ('ala', 'Islas Gland'),
    ('alb', 'Albania'),
    ('deu', 'Alemania'),
    ('and', 'Andorra'),
    ('ago', 'Angola'),
    ('aia', 'Anguilla'),
    ('ata', 'Antártida'),
    ('atg', 'Antigua y Barbuda'),
    ('ant', 'Antillas Holandesas'),
    ('sau', 'Arabia Saudí'),
    ('dza', 'Argelia'),
    ('arg', 'Argentina'),
    ('arm', 'Armenia'),
    ('abw', 'Aruba'),
    ('aus', 'Australia'),
    ('aut', 'Austria'),
    ('aze', 'Azerbaiyán'),
    ('bhs', 'Bahamas'),
    ('bhr', 'Bahréin'),
    ('bgd', 'Bangladesh'),
    ('brb', 'Barbados'),
    ('blr', 'Bielorrusia'),
    ('bel', 'Bélgica'),
    ('blz', 'Belice'),
    ('ben', 'Benin'),
    ('bmu', 'Bermudas'),
    ('btn', 'Bhután'),
    ('bol', 'Bolivia'),
    ('bih', 'Bosnia y Herzegovina'),
    ('bwa', 'Botsuana'),
    ('bvt', 'Isla Bouvet'),
    ('bra', 'Brasil'),
    ('brn', 'Brunéi'),
    ('bgr', 'Bulgaria'),
    ('bfa', 'Burkina Faso'),
    ('bdi', 'Burundi'),
    ('cpv', 'Cabo Verde'),
    ('cym', 'Islas Caimán'),
    ('khm', 'Camboya'),
    ('cmr', 'Camerún'),
    ('can', 'Canadá'),
    ('caf', 'República Centroafricana'),
    ('tcd', 'Chad'),
    ('cze', 'República Checa'),
    ('chl', 'Chile'),
    ('chn', 'China'),
    ('cyp', 'Chipre'),
    ('cxr', 'Isla de Navidad'),
    ('vat', 'Ciudad del Vaticano'),
    ('cck', 'Islas Cocos'),
    ('col', 'Colombia'),
    ('com', 'Comoras'),
    ('cod', 'Rep. Dem. del Congo'),
    ('cog', 'Congo'),
    ('cok', 'Islas Cook'),
    ('prk', 'Corea del Norte'),
    ('kor', 'Corea del Sur'),
    ('civ', 'Costa de Marfil'),
    ('cri', 'Costa Rica'),
    ('hrv', 'Croacia'),
    ('cub', 'Cuba'),
    ('dnk', 'Dinamarca'),
    ('dma', 'Dominica'),
    ('dom', 'República Dominicana'),
    ('ecu', 'Ecuador'),
    ('egy', 'Egipto'),
    ('slv', 'El Salvador'),
    ('are', 'Emir. Árabes Unidos'),
    ('eri', 'Eritrea'),
    ('svk', 'Eslovaquia'),
    ('svn', 'Eslovenia'),
    ('esp', 'España'),
    ('umi', 'Islas ultram. de EE.UU.'),
    ('usa', 'Estados Unidos'),
    ('est', 'Estonia'),
    ('eth', 'Etiopía'),
    ('fro', 'Islas Feroe'),
    ('phl', 'Filipinas'),
    ('fin', 'Finlandia'),
    ('fji', 'Fiyi'),
    ('fra', 'Francia'),
    ('gab', 'Gabón'),
    ('gmb', 'Gambia'),
    ('geo', 'Georgia'),
    ('sgs', 'I. Georgias del Sur'),
    ('gha', 'Ghana'),
    ('gib', 'Gibraltar'),
    ('grd', 'Granada'),
    ('grc', 'Grecia'),
    ('grl', 'Groenlandia'),
    ('glp', 'Guadalupe'),
    ('gum', 'Guam'),
    ('gtm', 'Guatemala'),
    ('guf', 'Guayana Francesa'),
    ('gin', 'Guinea'),
    ('gnq', 'Guinea Ecuatorial'),
    ('gnb', 'Guinea-Bissau'),
    ('guy', 'Guyana'),
    ('hti', 'Haití'),
    ('hmd', 'Islas Heard y McDonald'),
    ('hnd', 'Honduras'),
    ('hkg', 'Hong Kong'),
    ('hun', 'Hungría'),
    ('ind', 'India'),
    ('idn', 'Indonesia'),
    ('irn', 'Irán'),
    ('irq', 'Iraq'),
    ('irl', 'Irlanda'),
    ('isl', 'Islandia'),
    ('isr', 'Israel'),
    ('ita', 'Italia'),
    ('jam', 'Jamaica'),
    ('jpn', 'Japón'),
    ('jor', 'Jordania'),
    ('kaz', 'Kazajstán'),
    ('ken', 'Kenia'),
    ('kgz', 'Kirguistán'),
    ('kir', 'Kiribati'),
    ('kwt', 'Kuwait'),
    ('lao', 'Laos'),
    ('lso', 'Lesotho'),
    ('lva', 'Letonia'),
    ('lbn', 'Líbano'),
    ('lbr', 'Liberia'),
    ('lby', 'Libia'),
    ('lie', 'Liechtenstein'),
    ('ltu', 'Lituania'),
    ('lux', 'Luxemburgo'),
    ('mac', 'Macao'),
    ('mkd', 'ARY Macedonia'),
    ('mdg', 'Madagascar'),
    ('mys', 'Malasia'),
    ('mwi', 'Malawi'),
    ('mdv', 'Maldivas'),
    ('mli', 'Malí'),
    ('mlt', 'Malta'),
    ('flk', 'Islas Malvinas'),
    ('mnp', 'Islas Marianas del Norte'),
    ('mar', 'Marruecos'),
    ('mhl', 'Islas Marshall'),
    ('mtq', 'Martinica'),
    ('mus', 'Mauricio'),
    ('mrt', 'Mauritania'),
    ('myt', 'Mayotte'),
    ('mex', 'México'),
    ('fsm', 'Micronesia'),
    ('mda', 'Moldavia'),
    ('mco', 'Mónaco'),
    ('mng', 'Mongolia'),
    ('msr', 'Montserrat'),
    ('moz', 'Mozambique'),
    ('mmr', 'Myanmar'),
    ('nam', 'Namibia'),
    ('nru', 'Nauru'),
    ('npl', 'Nepal'),
    ('nic', 'Nicaragua'),
    ('ner', 'Níger'),
    ('nga', 'Nigeria'),
    ('niu', 'Niue'),
    ('nfk', 'Isla Norfolk'),
    ('nor', 'Noruega'),
    ('ncl', 'Nueva Caledonia'),
    ('nzl', 'Nueva Zelanda'),
    ('omn', 'Omán'),
    ('nld', 'Países Bajos'),
    ('pak', 'Pakistán'),
    ('plw', 'Palau'),
    ('pse', 'Palestina'),
    ('pan', 'Panamá'),
    ('png', 'Papúa Nueva Guinea'),
    ('pry', 'Paraguay'),
    ('per', 'Perú'),
    ('pcn', 'Islas Pitcairn'),
    ('pyf', 'Polinesia Francesa'),
    ('pol', 'Polonia'),
    ('prt', 'Portugal'),
    ('pri', 'Puerto Rico'),
    ('qat', 'Qatar'),
    ('gbr', 'Reino Unido'),
    ('reu', 'Reunión'),
    ('rwa', 'Ruanda'),
    ('rou', 'Rumania'),
    ('rus', 'Rusia'),
    ('esh', 'Sahara Occidental'),
    ('slb', 'Islas Salomón'),
    ('wsm', 'Samoa'),
    ('asm', 'Samoa Americana'),
    ('kna', 'San Cristóbal y Nevis'),
    ('smr', 'San Marino'),
    ('spm', 'San Pedro y Miquelón'),
    ('vct', 'San Vicente y las Granadinas'),
    ('shn', 'Santa Helena'),
    ('lca', 'Santa Luc?a'),
    ('stp', 'Santo Tomé y Príncipe'),
    ('sen', 'Senegal'),
    ('scg', 'Serbia y Montenegro'),
    ('syc', 'Seychelles'),
    ('sle', 'Sierra Leona'),
    ('sgp', 'Singapur'),
    ('syr', 'Siria'),
    ('som', 'Somalia'),
    ('lka', 'Sri Lanka'),
    ('swz', 'Suazilandia'),
    ('zaf', 'Sudáfrica'),
    ('sdn', 'Sudán'),
    ('swe', 'Suecia'),
    ('che', 'Suiza'),
    ('sur', 'Surinam'),
    ('sjm', 'Svalbard y Jan Mayen'),
    ('tha', 'Tailandia'),
    ('twn', 'Taiwán'),
    ('tza', 'Tanzania'),
    ('tjk', 'Tayikistán'),
    ('iot', 'T. Británico del O. Índico'),
    ('atf', 'T. Australes Franceses'),
    ('tls', 'Timor Oriental'),
    ('tgo', 'Togo'),
    ('tkl', 'Tokelau'),
    ('ton', 'Tonga'),
    ('tto', 'Trinidad y Tobago'),
    ('tun', 'Túnez'),
    ('tca', 'Islas Turcas y Caicos'),
    ('tkm', 'Turkmenistán'),
    ('tur', 'Turquía'),
    ('tuv', 'Tuvalu'),
    ('ukr', 'Ucrania'),
    ('uga', 'Uganda'),
    ('ury', 'Uruguay'),
    ('uzb', 'Uzbekistán'),
    ('vut', 'Vanuatu'),
    ('ven', 'Venezuela'),
    ('vnm', 'Vietnam'),
    ('vgb', 'I. Vírgenes Británicas'),
    ('vir', 'I. Vírgenes de los EE.UU.'),
    ('wlf', 'Wallis y Futuna'),
    ('yem', 'Yemen'),
    ('dji', 'Yibuti'),
    ('zmb', 'Zambia'),
    ('zwe', 'Zimbabue'),
)

FORMADDR_CHOICES = (
    ('D', 'D.'),
    ('DA', 'Dª'),
    ('DR', 'Dr'),
    ('DX', 'Dra.'),
    ('E', 'Emmo.'),
    ('EM', 'Emma.'),
    ('EX', 'Excmo.'),
    ('EY', 'Excma.'),
    ('I', 'Ilmo.'),
    ('E', 'Exmo.'),
    ('S', 'S.A.R.'),
    ('SE', 'S.E.'),
    ('SI', 'S.I.'),
    ('SM', 'S.M.'),
    ('SR', 'Sr.'),
    ('SX', 'Sra.'),
    ('SS', 'S.S.')
)

GENDER_CHOICES = (
    ('M', 'Hombre'),
    ('F', 'Mujer')
)

VIA_CHOICES = (
    ("A", "Avenida"),
    ("AT", "Atajo"),
    ("B", "Barrio"),
    ("BA", "Bajada"),
    ("BAR", "Barranco"),
    ("C", "Calle"),
    ("CA", "Camino"),
    ("CAN", "Canal"),
    ("CI", "Cinturón"),
    ("CR", "Callejón"),
    ("CS", "Cuesta"),
    ("CT", "Carretera"),
    ("D", "Bajada"),
    ("DI", "Dique"),
    ("E", "Entidad Autoidentificante"),
    ("EM", "Estación Metro"),
    ("ES", "Escaleras"),
    ("ESC", "Escollera"),
    ("ESP", "Espigón"),
    ("EST", "Estación"),
    ("F", "Fuente"),
    ("G", "Gran Vía"),
    ("GA", "Galería"),
    ("GR", "Grupo"),
    ("H", "Habitáculo"),
    ("J", "Jardines"),
    ("JA", "Jardín"),
    ("M", "Mirador"),
    ("ME", "Mercado"),
    ("MU", "Muelle"),
    ("N", "Nudo"),
    ("P", "Pantalan"),
    ("PA", "Parque"),
    ("PAS", "Paso"),
    ("PAT", "Patio"),
    ("PAV", "Pabellón"),
    ("PD", "Subida"),
    ("PDI", "Pasage"),
    ("PASE", "Paseo"),
    ("PL", "Plaza"),
    ("LL", "Llano"),
    ("PLA", "Placita"),
    ("PO", "Polígono"),
    ("PU", "Puente"),
    ("PUE", "Puerto"),
    ("PO", "Pòrticos"),
    ("PT", "Puerta"),
    ("PASA", "Pasage"),
    ("PLAY", "Playa"),
    ("R", "Rincón"),
    ("RA", "Rambla"),
    ("RO", "Ronda"),
    ("AC", "Acequia"),
    ("RI", "Riera"),
    ("RO", "Rotonda"),
    ("S", "Salón"),
    ("SE", "Sector"),
    ("T", "Torrente"),
    ("TR", "Travesera"),
    ("TRA", "Travesía"),
    ("TU", "Túnel"),
    ("U", "Urbanización"),
    ("VF", "Vía Ferrocarril"),
    ("VI", "Vía"),
    ("VIA", "Viaducto"),
    ("VIAL", "Vial")
)
